'core:algorithm':
  - changed-files:
      - any-glob-to-any-file: ['src/lib/problems/**/*']

'core:ui':
  - changed-files:
      - any-glob-to-any-file: ['src/components/**/*', 'src/app/**/*', 'styles/**/*']

'dx:ci':
  - changed-files:
      - any-glob-to-any-file: ['.github/**/*', 'scripts/**/*']

'dx:deps':
  - changed-files:
      - any-glob-to-any-file: ['package.json', 'pnpm-lock.yaml']

'docs':
  - changed-files:
      - any-glob-to-any-file: ['docs/**/*', '*.md']
