import { AlgorithmMode, ContainerInput } from './types';

export const MODES = [
  {
    value: AlgorithmMode.CLASSIC,
    label: '经典双指针',
  },
  {
    value: AlgorithmMode.FAST_SKIP,
    label: '快速跳跃双指针',
  },
  {
    value: AlgorithmMode.SORT_INDEX,
    label: '排序 + 极值索引',
  },
];

export const CLASSIC_CODE = [
  'function maxArea(height: number[]): number {',
  '  let left = 0;',
  '  let right = height.length - 1;',
  '  let maxResult = 0;',
  '',
  '  while (left < right) {',
  '    const currentHeight = Math.min(height[left], height[right]);',
  '    const currentWidth = right - left;',
  '    const currentArea = currentHeight * currentWidth;',
  '',
  '    maxResult = Math.max(maxResult, currentArea);',
  '',
  '    if (height[left] < height[right]) {',
  '      left++;',
  '    } else {',
  '      right--;',
  '    }',
  '  }',
  '',
  '  return maxResult;',
  '}',
];

export const FAST_SKIP_CODE = [
  'function maxArea2(height: number[]): number {',
  '  let left = 0;',
  '  let right = height.length - 1;',
  '  let maxResult = 0;',
  '',
  '  while (left < right) {',
  '    const hLeft = height[left];',
  '    const hRight = height[right];',
  '',
  '    const minHeight = hLeft < hRight ? hLeft : hRight;',
  '    const currentArea = minHeight * (right - left);',
  '    if (currentArea > maxResult) {',
  '      maxResult = currentArea;',
  '    }',
  '',
  '    if (hLeft < hRight) {',
  '      do {',
  '        left++;',
  '      } while (left < right && height[left] <= minHeight);',
  '    } else {',
  '      do {',
  '        right--;',
  '      } while (left < right && height[right] <= minHeight);',
  '    }',
  '  }',
  '',
  '  return maxResult;',
  '}',
];

export const SORT_INDEX_CODE = [
  'function maxArea3(height: number[]): number {',
  '  const n = height.length;',
  '  const indices = new Int32Array(n);',
  '  for (let i = 0; i < n; i++) {',
  '    indices[i] = i;',
  '  }',
  '',
  '  indices.sort((a, b) => height[b] - height[a]);',
  '',
  '  let maxResult = 0;',
  '  let minIdx = n;',
  '  let maxIdx = -1;',
  '',
  '  for (let i = 0; i < n; i++) {',
  '    const originalIdx = indices[i];',
  '',
  '    if (originalIdx < minIdx) minIdx = originalIdx;',
  '    if (originalIdx > maxIdx) maxIdx = originalIdx;',
  '',
  '    const dist = Math.max(originalIdx - minIdx, maxIdx - originalIdx);',
  '    const area = height[originalIdx] * dist;',
  '',
  '    if (area > maxResult) {',
  '      maxResult = area;',
  '    }',
  '  }',
  '',
  '  return maxResult;',
  '}',
];

export const LEGEND_ITEMS = [
  { colorBg: 'bg-cyan-500', label: '左侧边界 (L)' },
  { colorBg: 'bg-purple-500', label: '右侧边界 (R)' },
  { colorBg: 'bg-emerald-500', label: '当前处理元素 (Curr)' },
];

export const DEFAULT_INPUT: ContainerInput = { height: [1, 8, 6, 2, 5, 4, 8, 3, 7] };
