name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: Release Please
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: googleapis/release-please-action@v4
        with:
          release-type: node
          skip-github-release: false
          skip-github-pull-request: false
          token: ${{ secrets.GITHUB_TOKEN }}
